name: ChestShopExtras
version: '1.1.0'
main: com.github.orelii.chestshopextras.ChestShopExtras
api-version: '1.21'
authors: [ Oreli ]
description: Adds useful features to the ChestShop plugin
website: https://github.com/Orelii
depend: [ ChestShop, GriefPrevention ]
softdepend:
  - GriefPrevention
  - HuskClaims

commands:
  version:
    description: "Displays plugin version"
    usage: "/version"
    aliases: [v]
  shopshare:
    description: "Main command to manage shopshare access"
    usage: "/shopshare [add/remove/list/help]"
  discount:
    description: "Main command to manage shop discounts"
    usage: "/discount [add/remove/list/help"